const avengers = {
  'Capitão América': {
    poderes: [
      'Força sobre-humana',
      'Agilidade sobre-humana',
      'Resistência sobre-humana',
      'Fator de cura acelerado',
      'Maestria em combate corpo a corpo',
      'Especialista em tática e estratégia militar',
    ],
    identidadeSecreta: 'Steve Rogers',
    anoEntradaVingadores: 1963,
    localNascimento: 'Brooklyn, Nova York, EUA',
    idade: 100,
    cidadeAtuacao: 'Nova York, EUA',
    nomesHeroiAlternativos: ['O Sentinela da Liberdade', 'Super-Soldado'],
    status: 'Ativo',
    arquiInimigo: 'Caveira Vermelha',
    paresRomanticos: ['Peggy Carter', 'Sharon Carter'],
  },
  'Homem de Ferro': {
    poderes: [
      'Armadura tecnológica avançada com diversos recursos',
      'Voo',
      'Repulsores de energia',
      'Inteligência artificial avançada',
      'Gênio em engenharia e tecnologia',
    ],
    identidadeSecreta: 'Tony Stark',
    anoEntradaVingadores: 1963,
    localNascimento: 'Manhattan, Nova York, EUA',
    idade: 55,
    cidadeAtuacao: 'Diversas, principalmente Stark City, Califórnia, EUA',
    nomesHeroiAlternativos: ['Homem de Ferro Dourado', 'Extremis'],
    status: 'Falecido',
    arquiInimigo: 'Mandarim',
    paresRomanticos: ['Pepper Potts', 'Virginia Potts'],
  },
  Hulk: {
    poderes: [
      'Força sobre-humana colossal (aumentada com a raiva)',
      'Invulnerabilidade',
      'Fator de cura regenerativo',
      'Agilidade surpreendente para seu tamanho',
      'Absorção de energia',
    ],
    identidadeSecreta: 'Bruce Banner',
    anoEntradaVingadores: 1964,
    localNascimento: 'Dayton, Ohio, EUA',
    idade: 55,
    cidadeAtuacao: 'Diversas, geralmente se escondendo de seus inimigos',
    nomesHeroiAlternativos: ['Incrível Hulk', 'Professor Hulk', 'Joe Fixer'],
    status: 'Ativo',
    arquiInimigo: 'Líder',
    paresRomanticos: ['Betty Ross', 'Marlo Chandler'],
  },
  Thor: {
    poderes: [
      'Força sobre-humana',
      'Velocidade sobre-humana',
      'Invulnerabilidade',
      'Controle do clima',
      'Voo com o Mjolnir (martelo mágico)',
      'Longa vida',
    ],
    identidadeSecreta: 'Príncipe Odinson',
    anoEntradaVingadores: 1965,
    localNascimento: 'Asgard, Reino Celestial',
    idade: 5000,
    cidadeAtuacao: 'Midgard (Terra) e Asgard',
    nomesHeroiAlternativos: ['Deus do Trovão', 'Poderoso Thor'],
    status: 'Ativo',
    arquiInimigo: 'Loki',
    paresRomanticos: ['Lady Sif', 'Jane Foster'],
  },
  'Homem Aranha': {
    poderes: [
      'Força, agilidade e reflexos sobre-humanos',
      'Sentido-aranha (alerta precoce de perigo)',
      'Habilidade de se agarrar em superfícies',
      'Produção de teias sintéticas resistentes e elásticas',
    ],
    identidadeSecreta: 'Peter Parker',
    anoEntradaVingadores: 1965,
    localNascimento: 'Queens, Nova York, EUA',
    idade: 25,
    cidadeAtuacao: 'Nova York, EUA',
    nomesHeroiAlternativos: ['Cabeça de Teia', 'Aracnide', 'Teioso'],
    status: 'Ativo',
    arquiInimigo: 'Doutor Octopus',
    paresRomanticos: ['Mary Jane Watson', 'Gwen Stacy', 'Liz Allan'],
  },
};

export default avengers;
